### ISSUE TITLE
Got some trouble in grid_strategy

### ISSUE THREAD

**Issue by lions-heart** [Ferenas/CPN#5]
Does hide_patch really work? It has two options to cut the image into patches of size 224 or 448. I got several questions. first: Images are of different sizes in the voc12 dataset，When the patch_size is 224, only four image patches can be obtained for per image, which is not same as shown in Figure 1. And there are no other sizes here. And the second one is '**grid_size = grid_sizes[random.randint(0, len(grid_sizes) - 1)]**' could not reach the result of random at all.

**Comment by SII-Ferenas** [comment]
Hi, thanks for your comment. Note that the grid patch strategy is after Cropping them to 448*448, Figure 1 is only an illustration for our motivation. In the experiments part, we use a set K to contain the possible patch size, as shown in Figure 7. You can modify it to any size you like. According to my experiments, you may get higher performance to use [14,28,56,112] instead of simply using [56,112].
